declare const classNames: {
  readonly mdcTouchTargetWrapper: "mdcTouchTargetWrapper";
  readonly mdcRadio: "mdcRadio";
  readonly mdcRadioNativeControl: "mdcRadioNativeControl";
  readonly mdcRadioBackground: "mdcRadioBackground";
  readonly mdcRadioOuterCircle: "mdcRadioOuterCircle";
  readonly mdcRadioInnerCircle: "mdcRadioInnerCircle";
  readonly mdcRadioRipple: "mdcRadioRipple";
  readonly mdcRadioTouch: "mdcRadioTouch";
  readonly mdcRadioDisabled: "mdcRadioDisabled";
  readonly mdcRippleSurfaceTestEdgeVarBug: "mdcRippleSurfaceTestEdgeVarBug";
  readonly mdcRippleUpgraded: "mdcRippleUpgraded";
  readonly mdcRippleUpgradedUnbounded: "mdcRippleUpgradedUnbounded";
  readonly mdcRippleUpgradedForegroundActivation: "mdcRippleUpgradedForegroundActivation";
  readonly mdcRippleUpgradedForegroundDeactivation: "mdcRippleUpgradedForegroundDeactivation";
  readonly mdcRippleUpgradedBackgroundFocused: "mdcRippleUpgradedBackgroundFocused";
  readonly container: "container";
  readonly native: "native";
  readonly radio: "radio";
  readonly inner: "inner";
  readonly label: "label";
};
export = classNames;
