// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const noRipple: string;
export const label: string;
export const mdcRippleFgRadiusIn: string;
export const mdcRippleFgOpacityIn: string;
export const mdcRippleFgOpacityOut: string;
