compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  preact-cli@*:
    dependencies:
      mkdirp: "*"

supportedArchitectures:
  cpu:
    - current
    - x86
    - x64
    - arm64
    - ia32
  os:
    - current
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.6.0.cjs
