defaultSemverRangePrefix: ""

nodeLinker: node-modules

packageExtensions:
  preact-cli@*:
    dependencies:
      mkdirp: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

supportedArchitectures:
  os:
    - "current"
    - "darwin"
    - "linux"
    - "win32"
  cpu:
    - "current"
    - "x86"
    - "x64"
    - "arm64"
    - "ia32"

yarnPath: .yarn/releases/yarn-3.7.0.cjs
