defaultSemverRangePrefix: ""

nodeLinker: node-modules

packageExtensions:
  preact-cli@*:
    dependencies:
      mkdirp: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.7.0.cjs
