# Define stages
stages:
  - test
  - deploy

# Frontend yarn build & test
test-frontend:
  stage: test
  image: node@sha256:f0dfc4847f46d231e44948ded37521492439fd4ac19a6ef2597b9c79fe7a03a0
  before_script:
    - cd frontend
  script:
    - yarn
    - yarn build
  after_script:
    - cd ..

# Backend gradle build & test
test-backend:
  stage: test
  image: gradle:jdk11@sha256:220136bf04cbe814479ec15b981b2fc0b0c9b736548d8508abdf17dc05e6b0a7
  before_script:
    - cd backend
  script:
    - gradle build --no-daemon
  after_script:
    - cd ..

# Frontend deploy to firebase
deploy-frontend:
  stage: deploy
  image: node@sha256:f0dfc4847f46d231e44948ded37521492439fd4ac19a6ef2597b9c79fe7a03a0
  before_script:
    - cd frontend
    - yarn
    - yarn build
    - npm install -g firebase-tools
  script:
    - firebase deploy --token $FIREBASE_TOKEN
  after_script:
    - cd ..
  only:
    - tags

# Backend deploy needs to be made manually!
