// This file is automatically generated from your CSS. Any edits will be overwritten.
export const node: string;
export const nodeDisabled: string;
export const textClosed: string;
export const svg: string;
export const fab: string;
