// This file is automatically generated from your CSS. Any edits will be overwritten.
export const node: string;
export const rectSelected: string;
export const nodeClosed: string;
export const textClosed: string;
export const fClosed: string;
export const fDefault: string;
