import globalClassNames from "../../../style.d";
declare const classNames: typeof globalClassNames & {
    readonly mdcSwitchThumbUnderlay: "mdcSwitchThumbUnderlay";
    readonly mdcSwitchNativeControl: "mdcSwitchNativeControl";
    readonly mdcSwitch: "mdcSwitch";
    readonly mdcSwitchChecked: "mdcSwitchChecked";
    readonly mdcSwitchTrack: "mdcSwitchTrack";
    readonly mdcSwitchThumb: "mdcSwitchThumb";
    readonly mdcSwitchDisabled: "mdcSwitchDisabled";
    readonly mdcRippleSurfaceTestEdgeVarBug: "mdcRippleSurfaceTestEdgeVarBug";
    readonly mdcRippleUpgradedBackgroundFocused: "mdcRippleUpgradedBackgroundFocused";
    readonly mdcRippleUpgraded: "mdcRippleUpgraded";
    readonly mdcRippleUpgradedUnbounded: "mdcRippleUpgradedUnbounded";
    readonly mdcRippleUpgradedForegroundActivation: "mdcRippleUpgradedForegroundActivation";
    readonly mdcRippleUpgradedForegroundDeactivation: "mdcRippleUpgradedForegroundDeactivation";
    readonly container: "container";
    readonly noRipple: "noRipple";
    readonly label: "label";
};
export = classNames;
