// This file is automatically generated from your CSS. Any edits will be overwritten.
export const snack: string;
export const error: string;
export const success: string;
export const none: string;
export const btn: string;
