package statekeeper

const val EXAMPLE_NAME_SIZE = 140
const val EXAMPLE_DESC_SIZE = 280
const val EXAMPLE_FORMULA_SIZE = 1024
const val EXAMPLE_PARAM_SIZE = 512
const val EXAMPLE_CALC_NAME_SIZE = 64
const val MAX_EXAMPLE_COUNT = 128

const val SCORE_MAX_CALC_NAME_SIZE = EXAMPLE_CALC_NAME_SIZE
const val SCORE_MAX_FIELD_COUNT = 6
const val SCORE_MAX_KEY_SIZE = 50
const val SCORE_MAX_VALUE_SIZE = 10
const val SCORE_MAX_FORMULA_SIZE = EXAMPLE_FORMULA_SIZE
const val SCORE_FLUSH_DELAY_MS: Long = 1000 * 60 * 60 * 20
