// This file is automatically generated from your CSS. Any edits will be overwritten.
export const header: string;
export const logo: string;
export const mainLink: string;
export const spacer: string;
export const active: string;
