// This file is automatically generated from your CSS. Any edits will be overwritten.
export const dialog: string;
export const open: string;
export const container: string;
export const content: string;
export const actions: string;
