// This file is automatically generated from your CSS. Any edits will be overwritten.
export const control: string;
export const menu: string;
export const show: string;
export const delay1: string;
export const delay2: string;
export const delay3: string;
