name: Build and Deploy to kbar.app

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'backend/**'
      - '.github/**'
      - 'README.md'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd frontend && yarn && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KALKULIERBAR_8EDA1 }}'
          projectId: kalkulierbar-8eda1
          entryPoint: ./frontend
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
